  name: Deploy to Cloud Run

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Authenticate to GCP
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Set up gcloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: my-first-project-85838 

        - name: Build and push Docker image
          run: |
           gcloud builds submit --tag gcr.io/my-first-project-85838/flask-app ./app
        

        - name: Terraform Init
          run: terraform -chdir=./terraform/ init
    
        - name: Terraform Plan
          run: terraform -chdir=./terraform/ plan
    
        - name: Terraform Apply
          run: terraform -chdir=./terraform/ apply -auto-approve

        - name: Deploy to Cloud Runca
          run: |
            gcloud run deploy tp-app --image=europe-west1-docker.pkg.dev/my-first-project-85838/app\
              --platform=managed --region=europe-west1 --allow-unauthenticated