  name: Deploy to Cloud Run

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Authenticate to GCP
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Set up gcloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: my-first-project-85838 

        - name: Build and push Docker image
          run: |
            gcloud builds submit --tag europe-west1-docker.pkg.dev/my-first-project-85838 /cloud-run-source-deploy/tp-app

        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy tp-app --image=europe-west1-docker.pkg.dev/my-first-project-85838 /cloud-run-source-deploy/tp-app \
              --platform=managed --region=europe-west1 --allow-unauthenticated